import { Platform ,StyleSheet } from "react-native";

export const tabLayoutStyles = StyleSheet.create({
  tabBar: {
    height: 62,
    backgroundColor: "#ffffff",
    borderTopWidth: 1,
    borderTopColor: "#eef2f7",
    paddingTop: 5,
    paddingBottom: 4,
  },
  tabItem: {
    alignItems: "center",
    justifyContent: "center",
  },
  tabIconWrap: {
    width: 60,
    height: 53,
    alignItems: "center",
    justifyContent: "center",
  },
  iconBox: {
    width: 36,
    height: 30,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  iconBoxActive: {
    backgroundColor: "#f1f5f9",
  },
  tabLabel: {
    color: "#7b8794",
    fontSize: 9,
    lineHeight: 13,
    marginTop: 1,
  },
  tabLabelActive: {
    color: "#397bf2",
    fontWeight: "700",
  },
});

export const chatStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#ffffff" },
  screen: { flex: 1, backgroundColor: "#ffffff" },
  header: {
    height: 74,
    backgroundColor: "#ffffff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 9,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  backButton: { width: 48, height: 48, alignItems: "center", justifyContent: "center" },
  headerTitle: { color: "#111827", fontSize: 18, fontWeight: "500" },
  headerSpacer: { width: 48 },
  chatArea: { flex: 1, backgroundColor: "#f8fbff" },
  chatContent: { paddingHorizontal: 14, paddingTop: 16, paddingBottom: 18 },
  messageRow: { flexDirection: "row", marginBottom: 12 },
  rowUser: { justifyContent: "flex-end" },
  rowAI: { justifyContent: "flex-start" },
  userBubble: {
    maxWidth: "78%",
    borderRadius: 16,
    borderBottomRightRadius: 4,
    backgroundColor: "#397bf2",
    paddingHorizontal: 13,
    paddingVertical: 9,
  },
  userBubbleText: { color: "#ffffff", fontSize: 14, lineHeight: 20 },
  aiBubble: {
    maxWidth: "78%",
    borderRadius: 16,
    borderBottomLeftRadius: 4,
    backgroundColor: "#ffffff",
    paddingHorizontal: 13,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  aiBubbleText: { color: "#1f2937", fontSize: 14, lineHeight: 21 },
  loadingBubble: { flexDirection: "row", alignItems: "center", backgroundColor: "#f3f4f6" },
  imageBubble: {
    width: 190,
    height: 190,
    borderRadius: 16,
    borderBottomRightRadius: 4,
    backgroundColor: "#e9eef6",
    overflow: "hidden",
  },
  chatImage: { width: "100%", height: "100%" },
  previewContainer: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: "#ffffff",
    borderTopWidth: 1,
    borderTopColor: "#f1f4f8",
    alignItems: "center",
  },
  previewImage: { width: 50, height: 50, borderRadius: 6 },
  closePreview: { position: "absolute", top: 2, left: 54 },
  inputBar: {
    minHeight: 56,
    backgroundColor: "#ffffff",
    flexDirection: "row",
    alignItems: "flex-end",
    paddingHorizontal: 6,
    paddingTop: 7,
    paddingBottom: 7,
    gap: 4,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
  },
  toolButton: { width: 30, height: 40, alignItems: "center", justifyContent: "center" },
  inputBox: {
    flex: 1,
    minHeight: 38,
    maxHeight: 92,
    borderRadius: 8,
    backgroundColor: "#f1f4f8",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  input: {
    color: "#111827",
    fontSize: 14,
    lineHeight: 18,
    paddingVertical: Platform.OS === "ios" ? 9 : 6,
    textAlignVertical: "center",
  },
});

export const exploreStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  header: {
    height: 66,
    backgroundColor: "#ffffff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#eef2f7",
  },
  backButton: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    color: "#111827",
    fontSize: 18,
    fontWeight: "800",
  },
  headerIconButton: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  content: {
    flex: 1,
    backgroundColor: "#f3f9ff",
  },
  scrollContent: {
    paddingBottom: 70,
    paddingTop: 10,
  },
  knowledgeHero: {
    minHeight: 150,
    backgroundColor: "#f3f9ff",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 18,
    paddingHorizontal: 68,
    overflow: "hidden",
  },
  heroBackButton: {
    position: "absolute",
    left: 10,
    top: 34,
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 3,
  },
  heroRefreshButton: {
    position: "absolute",
    right: 14,
    top: 40,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 3,
  },
  heroTitle: {
    color: "#111827",
    fontSize: 26,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 8,
  },
  heroSubtitle: {
    color: "#647083",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
  },
  patternDotLarge: {
    position: "absolute",
    right: 44,
    top: 7,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#d5e8ff",
  },
  patternDotSmall: {
    position: "absolute",
    right: 88,
    top: 62,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#d5e8ff",
  },
  patternHex: {
    position: "absolute",
    width: 52,
    height: 52,
    borderWidth: 2,
    borderColor: "#dcecff",
    transform: [{ rotate: "30deg" }],
  },
  patternHexTop: {
    right: 16,
    top: 48,
  },
  patternHexBottom: {
    right: 98,
    top: 32,
    opacity: 0.75,
  },
  categoryGrid: {
    flexDirection: "row",
    gap: 10,
    backgroundColor: "#f3f9ff",
    borderBottomColor: "#e7eef8",
    borderBottomWidth: 1,
    paddingBottom: 10,
    paddingHorizontal: 14,
    paddingTop: 10,
  },
  categoryButton: {
    flex: 1,
    height: 34,
    borderRadius: 10,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#9bb6d9",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 9,
    elevation: 2,
  },
  categoryButtonActive: {
    backgroundColor: "#1677f2",
    shadowColor: "#1677f2",
    shadowOpacity: 0.28,
  },
  categoryText: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "800",
  },
  categoryTextActive: {
    color: "#ffffff",
  },
  mainKnowledgeCard: {
    borderRadius: 12,
    backgroundColor: "#ffffff",
    marginHorizontal: 4,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 14,
    shadowColor: "#9bb6d9",
    shadowOffset: { width: 0, height: 13 },
    shadowOpacity: 0.18,
    shadowRadius: 22,
    elevation: 5,
  },
  mainCardTop: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  mainIconCircle: {
    width: 62,
    height: 62,
    borderRadius: 31,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 13,
  },
  mainTitleWrap: {
    flex: 1,
  },
  mainKnowledgeTitle: {
    color: "#111827",
    fontSize: 21,
    fontWeight: "900",
    marginBottom: 7,
  },
  tagWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  blueTag: {
    color: "#1664c8",
    fontSize: 13,
    fontWeight: "900",
    backgroundColor: "#e6f1ff",
    borderRadius: 10,
    overflow: "hidden",
    paddingHorizontal: 9,
    paddingVertical: 3,
  },
  newsTag: {
    color: "#e11d48",
    fontSize: 12,
    fontWeight: "900",
    backgroundColor: "#ffe4e6",
    borderRadius: 10,
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  mainDescription: {
    color: "#5b6678",
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 21,
    marginBottom: 10,
  },
  knowledgeSection: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 13,
  },
  sectionIconCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#eaf2ff",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  warningIconCircle: {
    backgroundColor: "#fff0f0",
  },
  sectionContent: {
    flex: 1,
  },
  knowledgeSectionTitle: {
    color: "#111827",
    fontSize: 17,
    fontWeight: "900",
    marginBottom: 7,
  },
  tacticBullet: {
    color: "#374151",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 22,
  },
  cardDivider: {
    height: 1,
    backgroundColor: "#dce4ee",
  },
  dangerTagWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
  },
  dangerTag: {
    color: "#dc2626",
    fontSize: 12,
    fontWeight: "900",
    borderWidth: 1,
    borderColor: "#fecaca",
    backgroundColor: "#fff7f7",
    borderRadius: 12,
    overflow: "hidden",
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  safeStepRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginBottom: 7,
  },
  safeStepText: {
    flex: 1,
    color: "#374151",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 20,
  },
  infoStrip: {
    minHeight: 46,
    borderRadius: 12,
    backgroundColor: "#eaf2ff",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    gap: 8,
    marginTop: 8,
  },
  infoStripText: {
    flex: 1,
    color: "#1664c8",
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 18,
  },
  compactCardList: {
    marginHorizontal: 4,
    marginTop: 10,
    gap: 8,
  },
  moreHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginHorizontal: 17,
    marginTop: 16,
    marginBottom: 8,
  },
  moreTitle: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "900",
  },
  moreCount: {
    color: "#8aa4c5",
    fontSize: 12,
    fontWeight: "800",
  },
  compactCard: {
    minHeight: 68,
    borderRadius: 12,
    backgroundColor: "#ffffff",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 13,
    shadowColor: "#9bb6d9",
    shadowOffset: { width: 0, height: 9 },
    shadowOpacity: 0.13,
    shadowRadius: 16,
    elevation: 3,
  },
  compactIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  compactContent: {
    flex: 1,
  },
  compactTitle: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "900",
    marginBottom: 6,
  },
  compactTagRow: {
    flexDirection: "row",
    gap: 8,
  },
  blueTagSmall: {
    color: "#1664c8",
    fontSize: 12,
    fontWeight: "900",
    backgroundColor: "#e6f1ff",
    borderRadius: 9,
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  newsTagSmall: {
    color: "#e11d48",
    fontSize: 11,
    fontWeight: "900",
    backgroundColor: "#ffe4e6",
    borderRadius: 9,
    overflow: "hidden",
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  fixedTabBar: {
    flexGrow: 0,
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#eef2f7",
  },
  tabRow: {
    gap: 8,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 8,
    backgroundColor: "#ffffff",
  },
  tabButton: {
    height: 34,
    borderRadius: 17,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f4f7fb",
  },
  tabButtonActive: {
    backgroundColor: "#e8f1ff",
  },
  tabText: {
    color: "#334155",
    fontSize: 14,
    fontWeight: "700",
  },
  tabTextActive: {
    color: "#397bf2",
  },
  featuredCard: {
    borderRadius: 24,
    backgroundColor: "#ffffff",
    marginHorizontal: 14,
    marginTop: 14,
    padding: 18,
    shadowColor: "#9bb6d9",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
    elevation: 4,
  },
  featuredTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  featuredIcon: {
    width: 54,
    height: 54,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  featuredMeta: {
    alignItems: "flex-end",
  },
  featuredTagRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 3,
  },
  featuredTag: {
    color: "#397bf2",
    fontSize: 12,
    fontWeight: "800",
  },
  featuredScamTag: {
    color: "#607697",
    fontSize: 10,
    fontWeight: "900",
    backgroundColor: "#f1f5f9",
    borderRadius: 9,
    overflow: "hidden",
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  featuredTime: {
    color: "#8da0bb",
    fontSize: 12,
    fontWeight: "700",
  },
  featuredTitle: {
    color: "#111827",
    fontSize: 20,
    fontWeight: "900",
    lineHeight: 28,
  },
  featuredDescription: {
    color: "#607697",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 20,
    marginTop: 8,
  },
  featuredFooter: {
    height: 38,
    borderRadius: 13,
    backgroundColor: "#f2f7ff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 13,
    marginTop: 16,
  },
  featuredFooterText: {
    color: "#397bf2",
    fontSize: 13,
    fontWeight: "800",
  },
  quickCheckCard: {
    borderRadius: 20,
    backgroundColor: "#eaf2ff",
    marginHorizontal: 14,
    marginTop: 14,
    padding: 15,
  },
  quickCheckHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  quickCheckTitle: {
    color: "#1c4fba",
    fontSize: 14,
    fontWeight: "900",
  },
  quickCheckText: {
    color: "#607697",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 18,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 10,
  },
  sectionHeaderCompact: {
    marginTop: 8,
    marginBottom: 8,
  },
  sectionTitle: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "900",
  },
  sectionHint: {
    color: "#8da0bb",
    fontSize: 12,
    fontWeight: "800",
  },
  articleList: {
    marginHorizontal: 14,
    gap: 12,
  },
  paginationBar: {
    height: 52,
    borderRadius: 18,
    backgroundColor: "#ffffff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginHorizontal: 4,
    marginTop: 12,
    paddingHorizontal: 10,
  },
  pageButton: {
    minWidth: 86,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#edf4ff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    gap: 3,
  },
  pageButtonDisabled: {
    backgroundColor: "#f5f8fc",
  },
  pageButtonText: {
    color: "#397bf2",
    fontSize: 12,
    fontWeight: "900",
  },
  pageButtonTextDisabled: {
    color: "#b8c5d8",
  },
  pageIndicator: {
    color: "#607697",
    fontSize: 13,
    fontWeight: "900",
  },
  articleRow: {
    borderRadius: 18,
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  articleTopLine: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  articleIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  articleTextGroup: {
    flex: 1,
  },
  articleMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  articleTagGroup: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginRight: 8,
  },
  articleTag: {
    color: "#397bf2",
    fontSize: 11,
    fontWeight: "900",
  },
  articleScamTag: {
    color: "#607697",
    fontSize: 10,
    fontWeight: "900",
    backgroundColor: "#f1f5f9",
    borderRadius: 9,
    overflow: "hidden",
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  articleTime: {
    color: "#9aacc8",
    fontSize: 11,
    fontWeight: "800",
  },
  articleTitle: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "900",
    lineHeight: 20,
  },
  articleDescription: {
    color: "#607697",
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 18,
    marginTop: 10,
  },
  knowledgePreviewBlock: {
    borderRadius: 14,
    backgroundColor: "#f8fbff",
    paddingHorizontal: 11,
    paddingVertical: 9,
    marginTop: 10,
    gap: 7,
  },
  knowledgePreviewRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  knowledgePreviewLabel: {
    width: 58,
    color: "#397bf2",
    fontSize: 11,
    fontWeight: "900",
  },
  knowledgePreviewText: {
    flex: 1,
    color: "#5e7190",
    fontSize: 11,
    fontWeight: "700",
  },
  emptyCard: {
    minHeight: 190,
    borderRadius: 20,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    marginHorizontal: 14,
  },
  emptyTitle: {
    color: "#5e7190",
    fontSize: 15,
    fontWeight: "900",
    marginTop: 10,
  },
  emptyText: {
    color: "#9aacc8",
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
    marginTop: 5,
    lineHeight: 18,
  },
  detailContent: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 56,
  },
  articleHeroCard: {
    borderRadius: 24,
    backgroundColor: "#ffffff",
    padding: 18,
    marginBottom: 16,
    shadowColor: "#9bb6d9",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.1,
    shadowRadius: 18,
    elevation: 3,
  },
  articleHeroTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  detailIcon: {
    width: 54,
    height: 54,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  articleMetaPillGroup: {
    alignItems: "flex-end",
    gap: 5,
  },
  categoryPill: {
    minHeight: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 11,
  },
  categoryPillText: {
    fontSize: 12,
    fontWeight: "900",
  },
  scamTypePill: {
    minHeight: 26,
    borderRadius: 13,
    backgroundColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  scamTypePillText: {
    color: "#607697",
    fontSize: 11,
    fontWeight: "900",
  },
  sourceText: {
    color: "#8aa4c5",
    fontSize: 11,
    fontWeight: "800",
  },
  detailTitle: {
    color: "#111827",
    fontSize: 22,
    fontWeight: "900",
    lineHeight: 31,
  },
  detailSummary: {
    color: "#607697",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 20,
    marginTop: 10,
  },
  detailMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 14,
  },
  detailMetaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  detailMeta: {
    color: "#8aa4c5",
    fontSize: 12,
    fontWeight: "800",
  },
  detailBodyCard: {
    borderRadius: 22,
    backgroundColor: "#ffffff",
    padding: 16,
    minHeight: 260,
  },
  knowledgeGuideCard: {
    borderRadius: 22,
    backgroundColor: "#ffffff",
    padding: 16,
    marginBottom: 16,
  },
  bodySectionTitle: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 6,
  },
  guideSection: {
    borderBottomWidth: 1,
    borderBottomColor: "#edf2f7",
    paddingTop: 12,
    paddingBottom: 14,
  },
  guideSectionLast: {
    paddingTop: 12,
  },
  guideTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    marginBottom: 9,
  },
  guideTitle: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "900",
  },
  guideBullet: {
    color: "#334155",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 22,
    marginBottom: 3,
  },
  warningTagWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  warningTag: {
    borderRadius: 12,
    backgroundColor: "#fff4e6",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  warningTagText: {
    color: "#c56a00",
    fontSize: 12,
    fontWeight: "900",
  },
  checkRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 7,
    marginBottom: 8,
  },
  checkText: {
    flex: 1,
    color: "#334155",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 20,
  },
  paragraphBlock: {
    borderTopWidth: 1,
    borderTopColor: "#edf2f7",
    paddingTop: 14,
    marginTop: 12,
  },
  firstParagraphBlock: {
    borderTopWidth: 0,
    marginTop: 0,
    paddingTop: 0,
  },
  detailBodyText: {
    color: "#334155",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 24,
    marginBottom: 12,
  },
  officialButton: {
    height: 50,
    borderRadius: 16,
    backgroundColor: "#397bf2",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 14,
  },
  officialButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  loadingBox: {
    minHeight: 180,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  loadingText: {
    color: "#607697",
    fontSize: 12,
    fontWeight: "700",
  },
});

export const homeStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f8fbff",
  },
  container: {
    flex: 1,
    backgroundColor: "#f8fbff",
  },
  content: {
    paddingHorizontal: 15,
    paddingTop: 10,
    paddingBottom: 54,
  },
  header: {
    height: 68,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  logo: {
    width: 102,
    height: 58,
  },
  profileButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  profileAvatarImage: {
    width: "100%",
    height: "100%",
  },
  heroCard: {
    minHeight: 70,
    borderRadius: 14,
    backgroundColor: "#dceafe",
    justifyContent: "center",
    paddingHorizontal: 14,
    marginTop: 8,
    marginBottom: 17,
  },
  heroTitle: {
    color: "#2f62b9",
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 4,
  },
  heroSubtitle: {
    color: "#6c86aa",
    fontSize: 12,
  },
  sectionTitle: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "700",
    marginLeft: 4,
    marginBottom: 8,
  },
  quickGrid: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 18,
  },
  quickCard: {
    flex: 1,
    height: 78,
    borderRadius: 13,
    backgroundColor: "#ffffff",
    alignItems: "center",
    paddingTop: 9,
  },
  quickIconCircle: {
    width: 35,
    height: 35,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 5,
  },
  quickImageIcon: {
    width: 25,
    height: 25,
  },
  quickTitle: {
    color: "#1f2937",
    fontSize: 11,
    fontWeight: "800",
    textAlign: "center",
  },
  quickSubtitle: {
    color: "#9aa4b2",
    fontSize: 8,
    marginTop: 2,
    textAlign: "center",
  },
  topCard: {
    borderRadius: 14,
    backgroundColor: "#ffffff",
    paddingHorizontal: 19,
    paddingTop: 17,
    paddingBottom: 18,
    marginBottom: 16,
  },
  topHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  topTitle: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "700",
  },
  scamRow: {
    height: 35,
    flexDirection: "row",
    alignItems: "center",
  },
  rankBadge: {
    width: 14,
    height: 14,
    borderRadius: 3,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 9,
  },
  rankText: {
    color: "#ffffff",
    fontSize: 8,
    fontWeight: "900",
  },
  scamIconCircle: {
    width: 29,
    height: 29,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  scamName: {
    flex: 1,
    color: "#111827",
    fontSize: 14,
    fontWeight: "700",
  },
  scamCount: {
    width: 42,
    color: "#111827",
    fontSize: 16,
    textAlign: "right",
  },
  riskCard: {
    minHeight: 132,
    borderRadius: 14,
    backgroundColor: "#ffffff",
    paddingHorizontal: 15,
    paddingTop: 14,
    paddingBottom: 16,
    marginBottom: 16,
  },
  riskHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  riskTitle: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "800",
  },
  riskHint: {
    color: "#8a97a8",
    fontSize: 10,
  },
  emptyRiskState: {
    flex: 1,
    minHeight: 82,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  emptyRiskText: {
    color: "#8a97a8",
    fontSize: 12,
    fontWeight: "600",
  },
  advocacySection: {
    borderRadius: 16,
    backgroundColor: "#ffffff",
    padding: 12,
    marginBottom: 0,
  },
  advocacyHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  advocacyTitle: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "900",
  },
  advocacySubtitle: {
    color: "#8a97a8",
    fontSize: 10,
    marginTop: 2,
  },
  sourceBadge: {
    width: 38,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#dceafe",
    justifyContent: "center",
    alignItems: "center",
  },
  sourceBadgeText: {
    color: "#397bf2",
    fontSize: 12,
    fontWeight: "900",
  },
  advocacyImageCard: {
    height: 250,
    borderRadius: 13,
    backgroundColor: "#f3f7fd",
    overflow: "hidden",
  },
  advocacyImage: {
    width: "100%",
    height: "100%",
  },
});

export const profileStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f8fbff",
  },
  container: {
    flex: 1,
    backgroundColor: "#f8fbff",
  },
  content: {
    paddingHorizontal: 14,
    paddingBottom: 62,
    paddingTop: 4,
  },
  header: {
    height: 66,
    backgroundColor: "#f8fbff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#eef2f7",
  },
  backButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    color: "#111827",
    fontSize: 18,
    fontWeight: "700",
  },
  headerSpacer: {
    width: 44,
  },
  profileCard: {
    minHeight: 112,
    borderRadius: 18,
    backgroundColor: "#ffffff",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    marginBottom: 12,
  },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#d9e0ee",
    overflow: "hidden",
    alignItems: "center",
    marginRight: 16,
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  avatarHead: {
    width: 27,
    height: 27,
    borderRadius: 14,
    backgroundColor: "#8193b1",
    marginTop: 11,
  },
  avatarBody: {
    width: 68,
    height: 38,
    borderRadius: 34,
    backgroundColor: "#8193b1",
    marginTop: 6,
  },
  profileInfo: {
    flex: 1,
  },
  name: {
    color: "#111827",
    fontSize: 17,
    fontWeight: "800",
    marginBottom: 5,
  },
  phone: {
    color: "#8aa4c5",
    fontSize: 12,
    marginBottom: 9,
  },
  statusPill: {
    alignSelf: "flex-start",
    minHeight: 26,
    borderRadius: 13,
    backgroundColor: "#edf4ff",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 9,
    gap: 5,
  },
  statusText: {
    color: "#397bf2",
    fontSize: 11,
    fontWeight: "800",
  },
  summaryRow: {
    height: 72,
    borderRadius: 16,
    backgroundColor: "#ffffff",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  summaryItem: {
    flex: 1,
    alignItems: "center",
  },
  summaryNumber: {
    color: "#111827",
    fontSize: 20,
    fontWeight: "900",
    marginBottom: 4,
  },
  summaryLabel: {
    color: "#8a97a8",
    fontSize: 11,
    fontWeight: "700",
  },
  summaryDivider: {
    width: 1,
    height: 34,
    backgroundColor: "#e2e8f0",
  },
  noticeCard: {
    minHeight: 72,
    borderRadius: 16,
    backgroundColor: "#dceafe",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    marginBottom: 12,
  },
  noticeIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  noticeTextWrap: {
    flex: 1,
  },
  noticeTitle: {
    color: "#2f62b9",
    fontSize: 13,
    fontWeight: "900",
    marginBottom: 4,
  },
  noticeText: {
    color: "#6c86aa",
    fontSize: 11,
    lineHeight: 16,
  },
  menuCard: {
    borderRadius: 18,
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
  },
  menuRow: {
    minHeight: 68,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#edf1f6",
  },
  lastMenuRow: {
    borderBottomWidth: 0,
  },
  menuIconBox: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#edf4ff",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  menuIconBoxDanger: {
    backgroundColor: "#fff0f3",
  },
  menuContent: {
    flex: 1,
  },
  menuTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  menuTitle: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "800",
  },
  menuTitleDanger: {
    color: "#ff4d6d",
  },
  menuDescription: {
    color: "#8a97a8",
    fontSize: 11,
    lineHeight: 15,
  },
  badge: {
    minWidth: 22,
    height: 18,
    borderRadius: 9,
    backgroundColor: "#397bf2",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
    marginLeft: 8,
  },
  vipBadge: {
    backgroundColor: "#111827",
  },
  badgeText: {
    color: "#ffffff",
    fontSize: 9,
    fontWeight: "900",
  },
});
export const reportsStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f8fbff",
  },
  header: {
    minHeight: 82,
    backgroundColor: "#f8fbff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#eef2f7",
  },
  headerTitle: {
    color: "#111827",
    fontSize: 22,
    fontWeight: "900",
    marginBottom: 4,
  },
  headerSubtitle: {
    color: "#8aa4c5",
    fontSize: 12,
    fontWeight: "700",
  },
  headerAction: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#397bf2",
    alignItems: "center",
    justifyContent: "center",
  },
  container: {
    flex: 1,
    backgroundColor: "#f8fbff",
  },
  content: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 84,
  },
  summaryRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  summaryCard: {
    flex: 1,
    height: 76,
    borderRadius: 18,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  summaryNumber: {
    color: "#111827",
    fontSize: 21,
    fontWeight: "900",
    marginBottom: 4,
  },
  summaryLabel: {
    color: "#8a97a8",
    fontSize: 11,
    fontWeight: "800",
  },
  noticeCard: {
    borderRadius: 18,
    backgroundColor: "#eaf2ff",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    marginBottom: 14,
  },
  noticeTextGroup: {
    flex: 1,
  },
  noticeTitle: {
    color: "#1c4fba",
    fontSize: 14,
    fontWeight: "900",
    marginBottom: 4,
  },
  noticeText: {
    color: "#607697",
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 18,
  },
  filterRow: {
    gap: 8,
    paddingBottom: 6,
  },
  filterButton: {
    height: 34,
    borderRadius: 17,
    paddingHorizontal: 14,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  filterButtonActive: {
    backgroundColor: "#397bf2",
  },
  filterText: {
    color: "#607697",
    fontSize: 13,
    fontWeight: "800",
  },
  filterTextActive: {
    color: "#ffffff",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 10,
    marginBottom: 10,
    paddingHorizontal: 2,
  },
  sectionTitle: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "900",
  },
  sectionHint: {
    color: "#8aa4c5",
    fontSize: 12,
    fontWeight: "800",
  },
  reportList: {
    gap: 12,
  },
  reportCard: {
    borderRadius: 20,
    backgroundColor: "#ffffff",
    padding: 14,
  },
  reportTopRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  typeIconBox: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#edf4ff",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  reportMain: {
    flex: 1,
  },
  reportTarget: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 4,
  },
  reportDate: {
    color: "#9aacc8",
    fontSize: 11,
    fontWeight: "700",
  },
  statusPill: {
    minHeight: 26,
    borderRadius: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
  },
  statusText: {
    fontSize: 11,
    fontWeight: "900",
  },
  reportReason: {
    color: "#607697",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 18,
    marginBottom: 12,
  },
  reportFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  footerTag: {
    height: 28,
    borderRadius: 14,
    backgroundColor: "#f5f8fc",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  footerTagText: {
    color: "#607697",
    fontSize: 11,
    fontWeight: "800",
  },
  riskTag: {
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    gap: 6,
  },
  riskDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  riskText: {
    fontSize: 11,
    fontWeight: "900",
  },
  emptyCard: {
    minHeight: 190,
    borderRadius: 20,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  emptyTitle: {
    color: "#5e7190",
    fontSize: 15,
    fontWeight: "900",
    marginTop: 10,
  },
  emptyText: {
    color: "#9aacc8",
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
    marginTop: 5,
    lineHeight: 18,
  },
});