import {  Platform ,StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f8fbff",
  },
  screen: {
    flex: 1,
    backgroundColor: "#f8fbff",
  },
  header: {
    height: 68,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
  },
  backButton: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    color: "#111827",
    fontSize: 17,
    fontWeight: "700",
  },
  editButton: {
    minWidth: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  editText: {
    color: "#397bf2",
    fontSize: 14,
    fontWeight: "800",
  },
  tabRow: {
    height: 40,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    marginBottom: 10,
  },
  tabButton: {
    flex: 1,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  tabButtonActive: {
    backgroundColor: "#e8f1ff",
  },
  tabText: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "700",
  },
  tabTextActive: {
    color: "#397bf2",
    fontWeight: "900",
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingHorizontal: 8,
    paddingBottom: 116,
  },
  blacklistCard: {
    minHeight: 82,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#9db0cf",
    backgroundColor: "#ffffff",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 12,
  },
  itemIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  lineIcon: {
    width: 26,
    height: 26,
  },
  itemInfo: {
    flex: 1,
  },
  itemValue: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 5,
  },
  itemNote: {
    color: "#8aa4c5",
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 2,
  },
  itemType: {
    color: "#8aa4c5",
    fontSize: 12,
    fontWeight: "700",
  },
  itemNoteText: {
    color: "#5e7190",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 3,
  },
  removeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#fff0f3",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  emptyCard: {
    minHeight: 190,
    borderRadius: 18,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    marginTop: 8,
  },
  emptyTitle: {
    color: "#5e7190",
    fontSize: 15,
    fontWeight: "900",
    marginTop: 10,
  },
  emptyText: {
    color: "#9aacc8",
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
    marginTop: 5,
  },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 9,
    paddingTop: 12,
    paddingBottom: 26,
    backgroundColor: "#f8fbff",
  },
  addButton: {
    height: 54,
    borderRadius: 14,
    backgroundColor: "#397bf2",
    alignItems: "center",
    justifyContent: "center",
  },
  addButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.45)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  modalCard: {
    width: "100%",
    maxWidth: 460,
    borderRadius: 22,
    backgroundColor: "#ffffff",
    padding: 20,
  },
  modalTitle: {
    color: "#111827",
    fontSize: 20,
    fontWeight: "900",
    marginBottom: 6,
  },
  modalSubtitle: {
    color: "#6b7280",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 20,
    marginBottom: 16,
  },
  typeSwitch: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 14,
  },
  typeButton: {
    flex: 1,
    height: 42,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#d8e4f4",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  typeButtonActive: {
    backgroundColor: "#397bf2",
    borderColor: "#397bf2",
  },
  typeButtonText: {
    color: "#5e7190",
    fontSize: 14,
    fontWeight: "800",
  },
  typeButtonTextActive: {
    color: "#ffffff",
  },
  modalInput: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: "#d8e4f4",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: "#111827",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 12,
    outlineStyle: "none" as any,
  },
  noteInput: {
    minHeight: 78,
    textAlignVertical: "top",
  },
  modalActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
  },
  cancelButton: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#d8e4f4",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  cancelButtonText: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "900",
  },
  saveButton: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    backgroundColor: "#397bf2",
    alignItems: "center",
    justifyContent: "center",
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  saveButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  lineCallbackContainer: {
  flex: 1,
  alignItems: "center",
  justifyContent: "center",
  backgroundColor: "#eef5ff",
  },
  lineCallbackText: {
  marginTop: 16,
  color: "#2f62b9",
  fontSize: 16,
  fontWeight: "700",
  },
  
});

export default styles;

export const lineQueryStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f8fbff",
  },
  scrollContent: {
    flexGrow: 1,
    backgroundColor: "#f8fbff",
    paddingHorizontal: 16,
    paddingBottom: 32,
  },
  backButton: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 24,
    marginLeft: -8,
  },
  queryCard: {
    borderRadius: 24,
    backgroundColor: "#ffffff",
    paddingHorizontal: 18,
    paddingTop: 24,
    paddingBottom: 18,
    alignItems: "center",
    shadowColor: "#9bb6d9",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
    elevation: 4,
  },
  iconCircle: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: "#edfdf3",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  lineIcon: {
    width: 44,
    height: 44,
  },
  title: {
    color: "#111827",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 5,
  },
  subtitle: {
    color: "#7b91b3",
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 18,
  },
  inputWrap: {
    width: "100%",
    height: 54,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#d8e4f4",
    backgroundColor: "#ffffff",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    gap: 9,
    marginBottom: 14,
  },
  input: {
    flex: 1,
    color: "#111827",
    fontSize: 16,
    fontWeight: "700",
  },
  queryButton: {
    width: "100%",
    height: 52,
    borderRadius: 15,
    backgroundColor: "#397bf2",
    alignItems: "center",
    justifyContent: "center",
  },
  queryButtonDisabled: {
    opacity: 0.6,
  },
  queryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
  tipCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 18,
    backgroundColor: "#eaf2ff",
    padding: 14,
    marginTop: 14,
  },
  tipTextGroup: {
    flex: 1,
  },
  tipTitle: {
    color: "#1c4fba",
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 3,
  },
  tipText: {
    color: "#607697",
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 18,
  },
  historyCard: {
    minHeight: 230,
    borderRadius: 22,
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
    paddingTop: 16,
    paddingBottom: 16,
    marginTop: 16,
  },
  historyHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  historyTitle: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "800",
  },
  historyMore: {
    color: "#5e7190",
    fontSize: 12,
    fontWeight: "800",
  },
  recordRow: {
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#eef2f7",
    paddingVertical: 13,
  },
  recordIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#eefaf1",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  recordLineIcon: {
    width: 18,
    height: 18,
  },
  recordContent: {
    flex: 1,
  },
  recordValue: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "800",
  },
  recordResult: {
    color: "#7b91b3",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 2,
  },
  recordTime: {
    color: "#9aacc8",
    fontSize: 12,
    fontWeight: "700",
  },
  emptyState: {
    flex: 1,
    minHeight: 150,
    alignItems: "center",
    justifyContent: "center",
    borderTopWidth: 1,
    borderTopColor: "#eef2f7",
  },
  emptyTitle: {
    color: "#5e7190",
    fontSize: 14,
    fontWeight: "800",
    marginTop: 8,
  },
  emptyText: {
    color: "#9aacc8",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 4,
  },
  resultScreen: {
    flex: 1,
    backgroundColor: "#f8fbff",
  },
  resultHeader: {
    height: 66,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
  },
  resultBackButton: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  resultHeaderTitle: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "700",
  },
  resultHeaderSpacer: {
    width: 48,
  },
  resultContent: {
    paddingHorizontal: 8,
    paddingBottom: 112,
  },
  riskBanner: {
    minHeight: 72,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    marginBottom: 18,
  },
  riskBannerText: {
    flex: 1,
    marginLeft: 14,
  },
  riskTitle: {
    fontSize: 16,
    fontWeight: "900",
    marginBottom: 5,
  },
  riskSubtitle: {
    color: "#8a97a8",
    fontSize: 11,
    fontWeight: "700",
  },
  lineIdentity: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 22,
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#d9e0ee",
    overflow: "hidden",
    alignItems: "center",
    marginRight: 16,
  },
  avatarHead: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#8193b1",
    marginTop: 9,
  },
  avatarBody: {
    width: 62,
    height: 34,
    borderRadius: 31,
    backgroundColor: "#8193b1",
    marginTop: 6,
  },
  lineInfo: {
    minWidth: 90,
  },
  resultValue: {
    color: "#111827",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 8,
  },
  resultMeta: {
    color: "#8aa4c5",
    fontSize: 12,
    fontWeight: "700",
  },
  resultCard: {
    minHeight: 112,
    borderRadius: 14,
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 14,
    marginBottom: 12,
  },
  scoreCard: {
    borderWidth: 1.5,
    borderColor: "#8fa5c5",
  },
  cardHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  resultCardTitle: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "900",
  },
  scoreText: {
    fontSize: 13,
    fontWeight: "900",
  },
  scoreTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: "#edf1f6",
    overflow: "hidden",
    marginBottom: 10,
  },
  scoreFill: {
    height: "100%",
    borderRadius: 4,
  },
  scoreDescription: {
    color: "#7b8794",
    fontSize: 12,
    fontWeight: "700",
  },
  resultCardText: {
    color: "#607697",
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 19,
    marginTop: 14,
  },
  actionBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 8,
    paddingTop: 10,
    paddingBottom: 18,
    backgroundColor: "#f8fbff",
  },
  secondaryAction: {
    flex: 1,
    height: 42,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#d8d8d8",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryActionText: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "800",
  },
  reportAction: {
    flex: 1,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#dc2f38",
    alignItems: "center",
    justifyContent: "center",
  },
  reportActionText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
});

export const loginStyles = StyleSheet.create({
  scrollContent: { 
    flexGrow: 1, 
    backgroundColor: "#eef5ff" 
  },
  container: { 
    flex: 1, 
    paddingHorizontal: 28, 
    paddingTop: 48, 
    paddingBottom: 40, 
    backgroundColor: "#eef5ff" 
  },
  logoContainer: { 
    alignItems: "center", 
    justifyContent: "center", 
    marginTop: 18, 
    marginBottom: 10 
  },
  logo: { 
    width: 250, 
    height: 160 
  },
  dividerRow: { 
    flexDirection: "row", 
    alignItems: "center", 
    marginVertical: 10 
  },
  line: { 
    flex: 1, 
    height: 1, 
    backgroundColor: "#d7e5f8" 
  },
  welcome: { 
    marginHorizontal: 14, 
    fontSize: 17, 
    color: "#2f62b9", 
    fontWeight: "800", 
    letterSpacing: 2 
  },
  subtitle: { 
    textAlign: "center", 
    color: "#6c86aa", 
    marginBottom: 18, 
    fontSize: 13 
  },
  inputBox: { 
    height: 48, 
    borderWidth: 1, 
    borderColor: "#dbe8f7", 
    borderRadius: 11, 
    backgroundColor: "#ffffff", 
    flexDirection: "row", 
    alignItems: "center", 
    paddingHorizontal: 14, 
    marginBottom: 12, 
    zIndex: 2 
  },
  input: { 
    flex: 1, 
    fontSize: 15, 
    color: "#1f2937" 
  },
  optionRow: { 
    flexDirection: "row", 
    marginBottom: 14, 
    justifyContent: "space-between" 
  },
  remember: { 
    color: "#6c86aa", 
    fontSize: 13 
  },
  forgot: { 
    color: "#397bf2", 
    fontSize: 13, 
    fontWeight: "700" 
  },
  loginButton: { 
    height: 50, 
    backgroundColor: "#397bf2", 
    borderRadius: 11, 
    justifyContent: "center", 
    alignItems: "center", 
    marginBottom: 16, 
    zIndex: 2 
  },
  loginText: { 
    color: "#fff", 
    fontSize: 21, 
    fontWeight: "bold", 
    letterSpacing: 4 
  },
  orText: { 
    marginHorizontal: 14, 
    color: "#8a97a8", 
    fontSize: 13 
  },
  socialRow: { 
    flexDirection: "row", 
    gap: 14, 
    marginVertical: 14 
  },
  socialButton: { 
    flex: 1, 
    height: 50, 
    backgroundColor: "#ffffff", 
    borderWidth: 1, 
    borderColor: "#e3edf9", 
    borderRadius: 11, 
    alignItems: "center", 
    justifyContent: "center", 
    flexDirection: "row" 
  },
  socialText: { 
    fontSize: 15, 
    color: "#1f2937", 
    fontWeight: "700" 
  },
  registerButton: { 
    height: 50, 
    borderWidth: 1, 
    borderColor: "#c9dcf5", 
    borderRadius: 11, 
    justifyContent: "center", 
    alignItems: "center", 
    backgroundColor: "#edf4ff", 
    marginTop: 4, 
    zIndex: 2 
  },
  registerText: { 
    fontSize: 18, 
    color: "#2f62b9", 
    fontWeight: "800" 
  },
  hexagonBg: { 
    position: "absolute", 
    left: 0, 
    bottom: -50, 
    width: 300, 
    height: 300, 
    opacity: 0.32, 
    zIndex: 0 
  },
  icon: { 
    width: 22, 
    height: 22, 
    marginRight: 10, 
    resizeMode: "contain" 
  },
  eyeImage: { 
    width: 22, 
    height: 22, 
    tintColor: "#6c86aa" 
  },
  socialIcon: { 
    width: 24, 
    height: 24, 
    marginRight: 8, 
    resizeMode: "contain" 
  },
  registerContent: { 
    flexDirection: "row", 
    alignItems: "center" 
  },
  registerIcon: { 
    width: 22, 
    height: 22, 
    marginRight: 10, 
    resizeMode: "contain" 
  },
  modalOverlay: { 
    flex: 1, 
    backgroundColor: "rgba(31, 41, 55, 0.32)", 
    alignItems: "center", 
    justifyContent: "center", 
    paddingHorizontal: 28 
  },
  modalCard: { 
    width: "100%", 
    borderRadius: 16, 
    backgroundColor: "#f8fbff", 
    paddingHorizontal: 20, 
    paddingTop: 22, 
    paddingBottom: 18 
  },
  modalTitle: { 
    color: "#1f2937", 
    fontSize: 20, 
    fontWeight: "700", 
    textAlign: "center", 
    marginBottom: 8 
  },
  modalSubtitle: { 
    color: "#6c86aa", 
    fontSize: 13, 
    textAlign: "center", 
    marginBottom: 18 
  },
  modalInputBox: { 
    height: 48, 
    borderWidth: 1, 
    borderColor: "#dbe8f7", 
    borderRadius: 11, 
    backgroundColor: "#fff", 
    flexDirection: "row", 
    alignItems: "center", 
    paddingHorizontal: 14, 
    marginBottom: 14 
  },
  modalConfirmButton: { 
    height: 48, 
    borderRadius: 11, 
    backgroundColor: "#397bf2", 
    alignItems: "center", 
    justifyContent: "center", 
    marginBottom: 10 
  },
  modalConfirmText: { 
    color: "#fff", 
    fontSize: 17, 
    fontWeight: "700", 
    letterSpacing: 2 
  },
  modalCancelButton: { 
    height: 42, 
    borderRadius: 11, 
    borderWidth: 1, 
    borderColor: "#c9dcf5", 
    backgroundColor: "#ffffff", 
    alignItems: "center", 
    justifyContent: "center" 
  },
  modalCancelText: { 
    color: "#2f62b9", 
    fontSize: 15, 
    fontWeight: "700" 
  },
});

export const messageQueryStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f8fbff",
  },
  container: {
    paddingHorizontal: 18,
    paddingBottom: 40,
  },
  header: {
    height: 68,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backButton: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: "#111827",
  },
  headerSpacer: {
    width: 46,
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 18,
    marginBottom: 16,
  },
  label: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 12,
  },
  textArea: {
    minHeight: 150,
    borderWidth: 1,
    borderColor: "#d8e4f4",
    borderRadius: 16,
    padding: 14,
    fontSize: 15,
    color: "#111827",
    textAlignVertical: "top",
    backgroundColor: "#ffffff",
    outlineStyle: "none" as any,
  },
  analyzeButton: {
    height: 54,
    borderRadius: 15,
    backgroundColor: "#397bf2",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 14,
  },
  analyzeButtonDisabled: {
    opacity: 0.6,
  },
  analyzeButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
  },
  resultCard: {
    borderRadius: 20,
    padding: 18,
    marginBottom: 16,
  },
  resultHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
  },
  resultTitleGroup: {
    flex: 1,
  },
  resultTitle: {
    fontSize: 22,
    fontWeight: "900",
  },
  resultStatus: {
    marginTop: 4,
    color: "#4b5563",
    fontSize: 13,
    fontWeight: "700",
  },
  scoreBox: {
    backgroundColor: "rgba(255,255,255,0.75)",
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
  },
  scoreRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  scoreLabel: {
    color: "#374151",
    fontSize: 14,
    fontWeight: "800",
  },
  scoreValue: {
    fontSize: 14,
    fontWeight: "900",
  },
  scoreTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: "#e5e7eb",
    overflow: "hidden",
  },
  scoreFill: {
    height: "100%",
    borderRadius: 4,
  },
  infoBox: {
    backgroundColor: "rgba(255,255,255,0.75)",
    borderRadius: 14,
    padding: 14,
  },
  infoTitle: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "900",
    marginTop: 8,
    marginBottom: 6,
  },
  infoText: {
    color: "#4b5563",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 20,
  },
  historyCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 16,
  },
  historyTitle: {
    color: "#111827",
    fontSize: 17,
    fontWeight: "900",
    marginBottom: 12,
  },
  emptyBox: {
    alignItems: "center",
    paddingVertical: 28,
  },
  emptyText: {
    color: "#9ca3af",
    fontSize: 14,
    fontWeight: "700",
    marginTop: 8,
  },
  recordRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#eef2f7",
    gap: 10,
  },
  recordContent: {
    flex: 1,
  },
  recordTitle: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "900",
  },
  recordText: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 3,
  },
  recordScore: {
    fontSize: 14,
    fontWeight: "900",
  },
});

export const modalStyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  link: {
    marginTop: 15,
    paddingVertical: 15,
  },
});

export const phoneQueryStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  container: {
    padding: 20,
    paddingBottom: 40,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 24,
    gap: 12,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#111827",
  },
  headerSubtitle: {
    marginTop: 4,
    fontSize: 14,
    color: "#6b7280",
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 18,
    marginBottom: 18,
  },
  label: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 10,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 14,
    paddingHorizontal: 14,
    backgroundColor: "#f9fafb",
  },
  input: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 10,
    fontSize: 16,
    color: "#111827",
    outlineStyle: "none" as any,
  },
  queryButton: {
    marginTop: 14,
    backgroundColor: "#2563eb",
    paddingVertical: 15,
    borderRadius: 14,
    alignItems: "center",
  },
  queryButtonDisabled: {
    opacity: 0.6,
  },
  queryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
  resultCard: {
    borderRadius: 18,
    padding: 18,
    marginBottom: 18,
  },
  resultHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    gap: 12,
  },
  resultTitleBox: {
    flex: 1,
  },
  resultTitle: {
    fontSize: 22,
    fontWeight: "900",
  },
  resultPhone: {
    marginTop: 4,
    fontSize: 15,
    color: "#374151",
  },
  resultInfo: {
    backgroundColor: "rgba(255,255,255,0.7)",
    borderRadius: 14,
    padding: 14,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  infoLabel: {
    fontSize: 14,
    color: "#6b7280",
  },
  infoValue: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
  },
  messageBox: {
    marginTop: 6,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.08)",
  },
  messageText: {
    fontSize: 14,
    lineHeight: 20,
    color: "#374151",
  },
  historyCard: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 18,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 14,
  },
  emptyBox: {
    alignItems: "center",
    paddingVertical: 28,
  },
  emptyText: {
    marginTop: 8,
    color: "#9ca3af",
    fontSize: 14,
  },
  historyItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  historyLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  historyPhone: {
    fontSize: 15,
    fontWeight: "800",
    color: "#111827",
  },
  historyCarrier: {
    marginTop: 2,
    fontSize: 12,
    color: "#6b7280",
  },
  historyLevel: {
    fontSize: 13,
    fontWeight: "800",
  },
});

export const premiumunlock = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f8fbff",
  },
  header: {
    height: 66,
    backgroundColor: "#f8fbff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#eef2f7",
  },
  backButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    color: "#111827",
    fontSize: 18,
    fontWeight: "700",
  },
  headerSpacer: {
    width: 44,
  },
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 22,
    paddingBottom: 24,
  },
  heroCard: {
    borderRadius: 20,
    backgroundColor: "#ffffff",
    alignItems: "center",
    paddingHorizontal: 22,
    paddingTop: 28,
    paddingBottom: 26,
    marginBottom: 14,
  },
  heroIcon: {
    width: 82,
    height: 82,
    borderRadius: 41,
    backgroundColor: "#edf4ff",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  title: {
    color: "#111827",
    fontSize: 24,
    fontWeight: "900",
    marginBottom: 8,
    letterSpacing: 1,
  },
  subtitle: {
    color: "#6c86aa",
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
  },
  previewCard: {
    borderRadius: 18,
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
    paddingTop: 16,
    marginBottom: 16,
  },
  sectionTitle: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 8,
    marginLeft: 2,
  },
  previewRow: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#edf1f6",
  },
  lastPreviewRow: {
    borderBottomWidth: 0,
  },
  previewIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#edf4ff",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  previewTextWrap: {
    flex: 1,
  },
  previewTitle: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 4,
  },
  previewText: {
    color: "#8a97a8",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "600",
  },
  backHomeButton: {
    height: 50,
    borderRadius: 14,
    backgroundColor: "#397bf2",
    alignItems: "center",
    justifyContent: "center",
  },
  backHomeText: {
    color: "#ffffff",
    fontSize: 17,
    fontWeight: "900",
    letterSpacing: 2,
  },
});
export const profiledetail = StyleSheet.create({
    safeArea: {
    flex: 1,
    backgroundColor: "#f8fbff",
  },
  container: {
    flex: 1,
    backgroundColor: "#f8fbff",
  },
  content: {
    paddingHorizontal: 14,
    paddingBottom: 30,
    paddingTop: 4,
  },
  header: {
    height: 66,
    backgroundColor: "#f8fbff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#eef2f7",
  },
  backButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    color: "#111827",
    fontSize: 18,
    fontWeight: "700",
  },
  headerSpacer: {
    width: 44,
  },
  saveButton: {
    minWidth: 56,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#e8f1ff",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  saveButtonDisabled: {
    backgroundColor: "#eef2f7",
  },
  saveButtonText: {
    color: "#397bf2",
    fontSize: 14,
    fontWeight: "800",
  },
  saveButtonTextDisabled: {
    color: "#94a3b8",
  },
  profileCard: {
    borderRadius: 18,
    backgroundColor: "#ffffff",
    alignItems: "center",
    paddingTop: 18,
    paddingBottom: 16,
    marginBottom: 16,
  },
  avatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: "#d9e0ee",
    overflow: "hidden",
    alignItems: "center",
    marginBottom: 12,
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  cameraBadge: {
    position: "absolute",
    right: 3,
    bottom: 3,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#397bf2",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#ffffff",
  },
  avatarHead: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#8193b1",
    marginTop: 12,
  },
  avatarBody: {
    width: 84,
    height: 46,
    borderRadius: 42,
    backgroundColor: "#8193b1",
    marginTop: 8,
  },
  name: {
    color: "#111827",
    fontSize: 18,
    fontWeight: "900",
    marginBottom: 5,
  },
  email: {
    color: "#8aa4c5",
    fontSize: 12,
    marginBottom: 12,
  },
  editHint: {
    minHeight: 28,
    borderRadius: 14,
    backgroundColor: "#edf4ff",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    gap: 5,
  },
  editHintText: {
    color: "#397bf2",
    fontSize: 11,
    fontWeight: "800",
  },
  sectionTitle: {
    color: "#8a97a8",
    fontSize: 12,
    fontWeight: "900",
    marginLeft: 4,
    marginBottom: 7,
  },
  card: {
    borderRadius: 18,
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
    marginBottom: 16,
  },
  infoRow: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "#edf1f6",
  },
  lastInfoRow: {
    borderBottomWidth: 0,
  },
  rowLabel: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 4,
  },
  rowValue: {
    color: "#8a97a8",
    fontSize: 11,
    fontWeight: "600",
  },
  securityRow: {
    minHeight: 66,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#edf1f6",
  },
  securityIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#edf4ff",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  securityIconDanger: {
    backgroundColor: "#fff0f3",
  },
  securityContent: {
    flex: 1,
  },
  dangerText: {
    color: "#ff4d6d",
  },
  calendarOverlay: {
    flex: 1,
    paddingTop: 244,
    paddingHorizontal: 52,
    backgroundColor: "rgba(248, 251, 255, 0.38)",
  },
  calendarCard: {
    borderRadius: 8,
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
    paddingTop: 16,
    paddingBottom: 14,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  calendarHeader: {
    height: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  yearPicker: {
    height: 34,
    borderRadius: 17,
    backgroundColor: "#edf4ff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    marginBottom: 13,
  },
  yearButton: {
    height: 28,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 3,
  },
  yearButtonText: {
    color: "#397bf2",
    fontSize: 10,
    fontWeight: "800",
  },
  yearTextButton: {
    minWidth: 78,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#ffffff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  yearText: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "900",
  },
  yearList: {
    maxHeight: 228,
  },
  yearListContent: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingBottom: 2,
  },
  yearOption: {
    width: "30.5%",
    height: 36,
    borderRadius: 18,
    backgroundColor: "#f5f8fc",
    alignItems: "center",
    justifyContent: "center",
  },
  yearOptionActive: {
    backgroundColor: "#397bf2",
  },
  yearOptionText: {
    color: "#647083",
    fontSize: 13,
    fontWeight: "800",
  },
  yearOptionTextActive: {
    color: "#ffffff",
    fontWeight: "900",
  },
  calendarTitle: {
    color: "#647083",
    fontSize: 11,
    fontWeight: "800",
  },
  weekRow: {
    flexDirection: "row",
    marginBottom: 10,
  },
  weekText: {
    flex: 1,
    color: "#c2cad7",
    fontSize: 8,
    fontWeight: "800",
    textAlign: "center",
  },
  daysGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  dayCell: {
    width: `${100 / 7}%`,
    height: 29,
    alignItems: "center",
    justifyContent: "center",
  },
  dayCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  selectedDay: {
    backgroundColor: "#ef553f",
  },
  dayText: {
    color: "#4b5563",
    fontSize: 12,
    fontWeight: "600",
  },
  selectedDayText: {
    color: "#ffffff",
    fontWeight: "900",
  },
  optionOverlay: {
    flex: 1,
    backgroundColor: "rgba(31, 41, 55, 0.28)",
    justifyContent: "center",
    paddingHorizontal: 38,
  },
  optionCard: {
    borderRadius: 18,
    backgroundColor: "#ffffff",
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 8,
  },
  optionTitle: {
    color: "#111827",
    fontSize: 17,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 12,
  },
  optionRow: {
    height: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#edf1f6",
  },
  optionText: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "800",
  },
  bindingCard: {
    borderRadius: 20,
    backgroundColor: "#ffffff",
    padding: 16,
  },
  bindingHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  bindingTitle: {
    color: "#111827",
    fontSize: 19,
    fontWeight: "900",
    marginBottom: 4,
  },
  bindingSubtitle: {
    color: "#8a97a8",
    fontSize: 12,
    fontWeight: "600",
  },
  closeButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#f1f4f8",
    alignItems: "center",
    justifyContent: "center",
  },
  bindingItem: {
    minHeight: 68,
    borderRadius: 16,
    backgroundColor: "#f8fbff",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  bindingIconGoogle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  googleIcon: {
    width: 24,
    height: 24,
  },
  bindingIconLine: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#22c55e",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  lineText: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "900",
  },
  bindingContent: {
    flex: 1,
  },
  bindingName: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 3,
  },
  bindingMeta: {
    color: "#8a97a8",
    fontSize: 11,
    fontWeight: "600",
  },
  bindButton: {
    minWidth: 56,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#397bf2",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  bindButtonText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
  },
  bindingHint: {
    borderRadius: 14,
    backgroundColor: "#edf4ff",
    flexDirection: "row",
    alignItems: "center",
    padding: 11,
    marginTop: 3,
    gap: 7,
  },
  bindingHintText: {
    flex: 1,
    color: "#6c86aa",
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "700",
  },
  passwordCard: {
    borderRadius: 20,
    backgroundColor: "#ffffff",
    padding: 16,
  },
  passwordInputBox: {
    height: 48,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#dbe8f7",
    backgroundColor: "#f8fbff",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    marginBottom: 10,
    gap: 9,
  },
  passwordInput: {
    flex: 1,
    color: "#111827",
    fontSize: 14,
    fontWeight: "600",
  },
  passwordSubmitButton: {
    height: 48,
    borderRadius: 14,
    backgroundColor: "#397bf2",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
  },
  passwordSubmitText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  verifyTargetBox: {
    borderRadius: 14,
    backgroundColor: "#edf4ff",
    padding: 12,
    marginBottom: 10,
  },
  verifyTargetLabel: {
    color: "#6c86aa",
    fontSize: 11,
    fontWeight: "800",
    marginBottom: 5,
  },
  verifyTargetText: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "900",
  },
});

export const register = StyleSheet.create({
    scrollContent: {
flexGrow: 1,
backgroundColor: "#eef5ff",
},
container: {
flex: 1,
paddingHorizontal: 28,
paddingTop: 48,
paddingBottom: 40,
backgroundColor: "#eef5ff",
},
logoContainer: {
alignItems: "center",
justifyContent: "center",
marginTop: 18,
marginBottom: 10,
},
logo: {
width: 250,
height: 160,
},
hexagonBg: {
position: "absolute",
left: 0,
bottom: -50,
width: 300,
height: 300,
opacity: 0.32,
zIndex: 0,
},
dividerRow: {
flexDirection: "row",
alignItems: "center",
marginVertical: 10,
},
line: {
flex: 1,
height: 1,
backgroundColor: "#d7e5f8",
},
welcome: {
marginHorizontal: 14,
fontSize: 17,
color: "#2f62b9",
fontWeight: "800",
letterSpacing: 2,
},
subtitle: {
textAlign: "center",
color: "#6c86aa",
marginBottom: 18,
fontSize: 13,
},
inputBox: {
height: 48,
borderWidth: 1,
borderColor: "#dbe8f7",
borderRadius: 11,
backgroundColor: "#ffffff",
flexDirection: "row",
alignItems: "center",
paddingHorizontal: 14,
marginBottom: 12,
zIndex: 1,
},
icon: {
width: 22,
height: 22,
marginRight: 10,
resizeMode: "contain",
},
input: {
flex: 1,
fontSize: 15,
color: "#1f2937",
},
eyeImage: {
width: 22,
height: 22,
tintColor: "#6c86aa",
},
messageText: {
color: "#dc2626",
fontSize: 14,
fontWeight: "700",
textAlign: "center",
marginBottom: 10,
},
registerButton: {
height: 50,
backgroundColor: "#397bf2",
borderRadius: 11,
justifyContent: "center",
alignItems: "center",
marginTop: 6,
marginBottom: 16,
zIndex: 2,
},
disabledButton: {
opacity: 0.6,
},
registerText: {
color: "#fff",
fontSize: 21,
fontWeight: "bold",
letterSpacing: 4,
},
orText: {
marginHorizontal: 14,
color: "#8a97a8",
fontSize: 13,
},
loginButton: {
height: 50,
borderWidth: 1,
borderColor: "#c9dcf5",
borderRadius: 11,
justifyContent: "center",
alignItems: "center",
backgroundColor: "#edf4ff",
marginTop: 4,
zIndex: 2,
},
loginText: {
fontSize: 18,
color: "#2f62b9",
fontWeight: "800",
},
});

export const resetPasswordStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 28,
    paddingTop: 42,
    backgroundColor: "#eef5ff",
    justifyContent: "flex-start",
    overflow: "hidden",
    ...(Platform.OS === "web"
      ? ({
          minHeight: "100dvh",
          overflowY: "auto",
          touchAction: "pan-y",
        } as any)
      : {}),
  },
  logoContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 18,
    marginBottom: 18,
  },
  logo: {
    width: 250,
    height: 160,
  },
  card: {
    borderRadius: 18,
    backgroundColor: "#ffffff",
    paddingHorizontal: 20,
    paddingVertical: 22,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
    zIndex: 2,
    marginTop: 0,
  },
  title: {
    color: "#1f2937",
    fontSize: 24,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 8,
    letterSpacing: 2,
  },
  subtitle: {
    color: "#6c86aa",
    fontSize: 13,
    textAlign: "center",
    marginBottom: 16,
  },
  stateBox: {
    alignItems: "center",
    gap: 10,
    paddingVertical: 18,
  },
  stateText: {
    color: "#6c86aa",
    fontSize: 14,
  },
  errorText: {
    color: "#d14343",
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
    marginVertical: 14,
  },
  successText: {
    color: "#1f2937",
    fontSize: 22,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 8,
  },
  successBox: {
    alignItems: "center",
    paddingTop: 8,
    paddingBottom: 12,
  },
  successIconCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#22c55e",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 18,
  },
  successIcon: {
    color: "#fff",
    fontSize: 42,
    fontWeight: "800",
    lineHeight: 46,
  },
  successDescription: {
    color: "#6c86aa",
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
  },
  emailBox: {
    minHeight: 40,
    borderRadius: 10,
    backgroundColor: "#edf4ff",
    justifyContent: "center",
    paddingHorizontal: 12,
    marginBottom: 14,
  },
  emailText: {
    color: "#2f62b9",
    fontSize: 14,
    textAlign: "center",
  },
  inputBox: {
    height: 48,
    borderWidth: 1,
    borderColor: "#dbe8f7",
    borderRadius: 11,
    backgroundColor: "#fff",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    marginBottom: 12,
    ...(Platform.OS === "web"
      ? ({
          touchAction: "manipulation",
        } as any)
      : {}),
  },
  icon: {
    width: 22,
    height: 22,
    marginRight: 10,
    resizeMode: "contain",
  },
  input: {
    flex: 1,
    color: "#1f2937",
    fontSize: 15,
    ...(Platform.OS === "web"
      ? ({
          touchAction: "manipulation",
        } as any)
      : {}),
  },
  eyeImage: {
    width: 22,
    height: 22,
    tintColor: "#6c86aa",
  },
  primaryButton: {
    height: 50,
    borderRadius: 11,
    backgroundColor: "#397bf2",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
  },
  primaryText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: 2,
  },
  secondaryButton: {
    height: 48,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#c9dcf5",
    backgroundColor: "#edf4ff",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryText: {
    color: "#2f62b9",
    fontSize: 16,
    fontWeight: "700",
  },
  hexagonBg: {
    position: "absolute",
    left: 0,
    bottom: -50,
    width: 300,
    height: 300,
    opacity: 0.32,
    zIndex: 0,
  },
});